version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio_data:/data
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://seq:12201"
    #     tag: "minio"
  postgres:
    image: postgres:16
    container_name: postgres_16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://seq:12201"
    #     tag: "postgres"
  #To add password to valeky, you need to mount the config file to the container
  #Valkey is the real open source version of redis ^^
  valkey:
    image: valkey/valkey:7.2
    container_name: valkey_7.2
    ports:
      - "6379:6379"
    volumes:
      - ./valkey_data:/data
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://seq:12201"
    #     tag: "valkey"
  # seq:
  #   image: datalust/seq:latest
  #   container_name: seq
  #   ports:
  #     - "5341:5341"
  #     - "8081:80"
  #   environment:
  #     ACCEPT_EULA: Y
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./seq_data:/data
