image: node:20-alpine

stages:
  - validate
  - build
  - pages

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

lint:
  stage: validate
  script:
    - pnpm install
    - pnpm run lint

build:
  stage: build
  script:
    - pnpm install
    - pnpm run build --filter=docs
  artifacts:
    paths:
      - ./apps/docs/out

pages:
  only:
    - main
  before_script:
    - echo "Deploying!"
  stage: pages
  image: alpine:latest
  script:
    - mv ./apps/docs/out public
  dependencies:
    - build
  artifacts:
    paths:
      - ./public
