image: node:20-alpine

stages:
  - typecheck
  - lint
  - build
  - pages

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

typecheck-docs:
  stage: typecheck
  script:
    - cd docs
    - pnpm install
    - pnpm run typecheck

typecheck-project:
  stage: typecheck
  script:
    - cd docs
    - pnpm install
    - pnpm run typecheck

lint-docs:
  stage: lint
  script:
    - cd docs
    - pnpm install
    - pnpm run lint

lint-project:
  stage: lint
  script:
    - cd docs
    - pnpm install
    - pnpm run lint

build-docs:
  stage: build
  script:
    - cd docs
    - pnpm install
    - pnpm run build
    - pnpm run export
    - mv out ../out
  needs:
    - lint-docs
  artifacts:
    paths:
      - ./out

build-project:
  stage: build
  script:
    - cd docs
    - pnpm install
    - pnpm run build
  needs:
    - lint-project

pages:
  only:
    - main
  before_script:
    - echo "Deploying!"
  stage: pages
  image: alpine:latest
  script:
    - mv out public
  dependencies:
    - build-docs
  artifacts:
    paths:
      - ./public
