version: "3.9"
services:
  push-db:
    build:
      context: ../../
      dockerfile: docker/production/push-db.dockerfile
    image: push-db-img
    container_name: push-db
    depends_on:
      - postgres

  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    image: reverse-proxy-img
    restart: always
    container_name: reverse-proxy
    volumes:
      - ./conf/nginx/certificates:/etc/nginx/certs
    ports:
      - ${PROXY_HTTP_PORT}:80
      - ${PROXY_HTTPS_PORT}:443
    links:
      - app
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "nginx-proxy"
    networks:
      default:
        aliases:
          - vimsnap.local

  app:
    platform: "linux/amd64"
    build:
      context: ../../
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    image: vimsnap-img
    container_name: vimsnap
    depends_on:
      - minio
      - postgres
      - valkey
      - seqgelf
      - seq
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "app"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - ${MINIO_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
      - ./conf/minio/init_minio_keys.sh:/init_minio_keys.sh
    depends_on:
      seqgelf:
        condition: service_started
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "minio"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    depends_on:
      seqgelf:
        condition: service_started
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "postgres"

  #To add password to valkey, you need to mount the config file to the container
  #Valkey is the real open source version of redis ^^
  valkey:
    image: valkey/valkey:7.2
    container_name: valkey
    volumes:
      - ./valkey_data:/data
      - ./conf/valkey/valkey.conf:/usr/local/etc/valkey/valkey.conf
    depends_on:
      seqgelf:
        condition: service_started
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "valkey"
    # change config file used by valkey
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - ${SEQ_PORT}:5341
      - ${SEQ_LOG_PORT}:80
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: ${SEQ_FIRSTRUN_ADMINPASSWORDHASH}
    volumes:
      - ./seq_data:/data
  seqgelf:
    image: datalust/seq-input-gelf
    container_name: seq_forwarder
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    ports:
      - ${SEQGELF_PORT}:${SEQGELF_PORT}/udp
    depends_on:
      seq:
        condition: service_started
