version: "3.9"
services:
  push-db:
    build:
      context: ../../
      dockerfile: docker/production/push-db.dockerfile
    image: push-db-img
    container_name: push-db
    env_file: .env
    depends_on:
      - postgres

  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    image: reverse-proxy-img
    restart: always
    container_name: proxy
    env_file: .env
    volumes:
      - ./conf/nginx/certificates:/etc/nginx/certs
    ports:
      - ${PROXY_HTTP_PORT}:80
      - ${PROXY_HTTPS_PORT}:443
    links:
      - app
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "nginx-proxy"
    networks:
      default:
        aliases:
          - vimsnap.local

  app:
    platform: "linux/amd64"
    build:
      context: ../../
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    environment:
      REDIS_URL: "localhost"
      REDIS_PASSWORD: "password"
      VALKEY_URL: "localhost" # change to vlakey in production environment
      VALKEY_PASSWORD: "AKQKSLDLK35SD313qSD61Q1S"
      RATE_LIMIT_WINDOW: "60"
      RATE_LIMIT_MAX: "100"
      HMAC_SECRET: "secret"
      NEXTAUTH_URL: "https://vimsnap.local:8443"
      NEXTAUTH_SECRET: "secret"
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/database" # change this with the name of container in production
      MINIO_ACCESS_KEY: "Sxmop8h_O4GD9ptJN2E" # change this with the access key of the minio service
      MINIO_SECRET_KEY: "BO_JOsSBePhEUjXe0JbImQncyMxK_tMl_Ld6GrGT" # change this with the secret key of the minio service
      MINIO_USE_SSL: "false"
      MINIO_PORT: "9000"
      MINIO_ENDPOINT: "minio" # change this with the name of container in production
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
      MINIO_ROOT_USER: "root" # change this with the root user of the minio service
      MINIO_ROOT_PASSWORD: "password" # change this with the root password of the minio service
      SEQ_URL: "http://seq:8081"
    working_dir: /app
    image: vimsnap-img
    env_file: .env
    container_name: vimsnap
    # extra_hosts:
    #   - "t3.local:reverse-proxy"
    depends_on:
      - minio
      - postgres
      - valkey
      - seqgelf
      - seq
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "app"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    # To setup the keys, you need to execute the folowing command : docker exec -it CONTAINER_ID sh /init_minio_keys.sh
    env_file: .env
    ports:
      - ${MINIO_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
      - ./conf/minio/init_minio_keys.sh:/init_minio_keys.sh
    depends_on:
      seqgelf:
        condition: service_started
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "minio"

  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    depends_on:
      seqgelf:
        condition: service_started
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "postgres"

  #To add password to valkey, you need to mount the config file to the container
  #Valkey is the real open source version of redis ^^
  valkey:
    image: valkey/valkey:7.2
    container_name: valkey
    volumes:
      - ./valkey_data:/data
      - ./conf/valkey/valkey.conf:/usr/local/etc/valkey/valkey.conf
    depends_on:
      seqgelf:
        condition: service_started
    env_file: .env
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "valkey"
    # change config file used by valkey
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]

  seq:
    image: datalust/seq:latest
    container_name: seq
    env_file: .env
    ports:
      - ${SEQ_PORT}:5341
      - ${SEQ_LOG_PORT}:80
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: ${SEQ_FIRSTRUN_ADMINPASSWORDHASH}
    volumes:
      - ./seq_data:/data

  seqgelf:
    image: datalust/seq-input-gelf
    container_name: seq_forwarder
    env_file: .env
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    ports:
      - ${SEQGELF_PORT}:${SEQGELF_PORT}/udp
    depends_on:
      seq:
        condition: service_started
