#! /bin/sh

"""
This script is used to initialize the minio keys for the production environment.
It will install the minio client (mc) and connect it to the minio server.
Then it will create a new user, attach a read write policy on it and generate a new key pair for the production user.
"""

# variables
MINIO_ADDR="http://localhost:9000"
MINIO_ALIAS="minio_dev"
MINIO_ROOT_USER="root"
MINIO_ROOT_PASSWORD="password"
MINIO_USER="produser"
MINIO_PASSWORD="prodpassword"
MINIO_NAME="prodkeys"
# this secret key were generated by python lib : minio-keygen
MINIO_ACCESS_KEY="Sxmop8h_O4GD9ptJN2E"
MINIO_SECRET_KEY="BO_JOsSBePhEUjXe0JbImQncyMxK_tMl_Ld6GrGT"
MINIO_ROOT_ACCESS_KEY="KhYRsb3hLv5UDKWZ5u0"
MINIO_ROOT_SECRET_KEY="dppfPZSXpSduIaC3JqDG2efCjuq9DcrsQE7rqbur"

set -e

# Connect mc (minio client) to minio server
echo "Connecting mc to minio server"
mc config host add $MINIO_ALIAS $MINIO_ADDR $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD

# create a new user for production
echo "Creating a new user for production"
mc admin user add minio_dev $MINIO_USER $MINIO_PASSWORD
# attache the new user to a read and write policy
# echo "Attaching read and write policy to the new user"
# echo "it's not implemented yet in the script, please attach the policy manually" 
mc admin policy attach $MINIO_ALIAS readonly --user $MINIO_USER
# create a new key pair for the new user
echo "Creating a new key pair for production user"
mc admin user svcacct add --access-key $MINIO_ACCESS_KEY --secret-key $MINIO_SECRET_KEY --name $MINIO_NAME $MINIO_ALIAS $MINIO_USER

