import Head from "next/head";

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Cryptalbum</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center"></main>
    </>
  );
}
